name: Mirror Dockerhub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1,7 *'

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: python
            folder: python
            repo: docker.io
          - image: postgres
            folder: postgres
            repo: docker.io/intland
          - image: postgres
            folder: postgre
            repo: docker.io
          - image: nodejs-windows
            repo: docker.io/harisshafiq08
            folder: nodejs-windows
          - image: node-nanoserver
            repo: docker.io/amitie10g
            folder: node-nanoserver
          - image: node
            repo: docker.io
            folder: node
          - image: nginx
            repo: docker.io
            folder: nginx
          - image: traefik
            repo: docker.io
            folder: traefik
          - image: postgis-windows
            repo: sokigo
            folder: postgresql-windows
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: actions/setup-go@v5
      - uses: imjasonh/setup-crane@v0.3
      - name: Mirror
        run: |
          for tag in $(cat ./images/${{ matrix.folder }}); do
            crane copy \
              ${{ matrix.repo }}/${{ matrix.image }}:$tag \
              ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:$tag
          done
